Refactoring + fakejuggler binary
leoleovich/3djuggler pull request #2
Opened 2019-08-07 10:06 UTC by abulimov

* Add .gitignore
* Move job definition into `lib`
* Refactor usage of strings as statuses, now they are consts
* Add `fakejuggler` binary to help with testing of UI/Clients

2019-08-07 14:24 UTC, yrk-lab requested changes

2019-08-07 14:24 UTC, yarikk commented on daemon.go
> +	"github.com/leoleovich/3djuggler/lib"
Not sure if a separate package is necessary... Can we at leaste have a meaningful name which would play nicely with types/constants in the package? "lib.JobStatus" is sort of too generic.

2019-08-08 11:51 UTC, abulimov commented
@yarikk I've renamed `lib` to `juggler` (best meaningful name I could come up with)

2019-08-16 14:28 UTC, leoleovich commented on main.go
> +		job:    &juggler.Job{Status: "Waiting for job"},
Maybe use your new type here?

2019-08-16 14:35 UTC, leoleovich requested changes

2019-08-16 14:35 UTC, leoleovich commented on main.go
> -					daemon.UpdateStatus("Button timeout")
This is still needed

2019-08-16 14:46 UTC, abulimov commented
Addressed comments

2019-08-16 14:54 UTC, leoleovich approved these changes
T.hanks!

2019-08-16 14:54 UTC, merged