Add /version handler which exports gitVersion
leoleovich/3djuggler pull request #6
Opened 2019-09-05 20:08 UTC by leoleovich

```
go run -ldflags "-X main.gitCommit=123" github.com/leoleovich/3djuggler
```
```
curl localhost:8888/version
123
```

2019-09-05 20:38 UTC, abulimov requested changes
Overall looks really good, but please add build instructions explaining how to build with real commit as a version to the README.md, and even maybe a Makefile to simplify the process.

2019-09-06 15:02 UTC, abulimov requested changes
I still think having makefile is better, but even without it doc should tell how to build, not run with gitCommit.

2019-09-06 15:02 UTC, abulimov commented on README.md
> +go run -ldflags "-X main.gitCommit=123" github.com/leoleovich/3djuggler
This runs juggler, not builds it.
I suggest using something like this instead:
```
export GIT_COMMIT=$(git rev-list -1 HEAD) && \
  go build -ldflags "-X main.gitCommit=$GIT_COMMIT" github.com/leoleovich/3djuggler
```

2019-09-06 18:50 UTC, merged

2021-07-14 09:55 UTC, yarikk reviewed
👍🏻