Pass through color from intern to info call
leoleovich/3djuggler pull request #7
Opened 2019-09-11 17:35 UTC by gsaraf

Propagate the requested color from the intern page to the info call.

2019-09-11 18:22 UTC, leoleovich reviewed
Please also update "fakejuggler" as it is used to test UI

2019-09-11 18:22 UTC, leoleovich commented on juggler/job.go
> +	Color        string             `json:"requested_color"`
Just color please :)

2019-09-11 18:25 UTC, leoleovich requested changes
Per comments

2019-09-11 22:48 UTC, gsaraf commented
Updated code - is that what you meant?

Thanks!

2019-09-11 22:48 UTC, gsaraf commented on juggler/job.go
> +	Color        string             `json:"requested_color"`
Done in update below.

2019-09-12 09:07 UTC, leoleovich commented
Thanks!

2019-09-12 09:08 UTC, merged